#!/bin/sh
if [ "`which docker`" = "" ]; then
  echo "Docker command line tool is not installed. Aborting..."
  exit 1
else
  DOCKER=`docker -v | sed 's/\(.*\) \(.*\), \(.*\) .*/\2/'`
  echo "Found docker version: $DOCKER"
fi
if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then
  if [ "$(docker ps | grep pg-$1)" ]; then
      echo "Container pg-$1 is running."
      echo "We'll log you in to the container and start up psql:"
      docker exec -it pg-$1 /bin/sh -c "psql -U postgres;/bin/sh"
      exit 0
  else
    if [ "$(docker ps -a | grep pg-$1)" ]; then
        echo "Container pg-$1 exists, but is not running."
        echo "Starting container: pg-$1"
        docker start pg-$1
        sleep 2
        echo "We'll log you in to the container and start up psql:"
        docker exec -it pg-$1 /bin/sh -c "psql -U postgres;/bin/sh"
        exit 0
    else
        echo "Container pg-$1 does not exist."
    fi
  fi
  FILE="$1.env"
  echo "Checking for $FILE file..."
  if [ ! -f "$FILE" ]; then
    echo ""
    echo "No config file ($FILE) was found, so we'll create one for you."
    echo ""
    read -p "Is this a primary server? (y/n): " PRIMARY
    echo ""
    if [[ ! "$PRIMARY" = "y" ]] && [[ ! "$PRIMARY" = "n" ]]; then
      echo "Invalid input. Please enter 'y' or 'n'."
      echo "Aborting..."
      exit 1
    fi
    read -p "Enter a password for the postgres user: " POSTGRES_PASSWORD
    read -p "Enter a password for the replication user (repuser): " REPUSER_PASSWORD
    if [[ "$PRIMARY" = "y" ]] || [[ "$PRIMARY" = "Y" ]]; then
      echo "HOST_TYPE=PRIMARY" > $FILE
    else
      echo "HOST_TYPE=SECONDARY" > $FILE
      read -p "Enter the IP address or domain name of the primary server: " HOST_IP
      read -p "Enter the port of the primary server: " HOST_PORT
      echo "HOST_IP=$HOST_IP" >> $FILE
      echo "HOST_PORT=$HOST_PORT" >> $FILE
    fi
    echo "REPUSER_PASSWORD=$POSTGRES_PASSWORD" >> $FILE
    echo "POSTGRES_PASSWORD=$REPUSER_PASSWORD" >> $FILE
    echo ""
  fi
  echo Starting PostgreSQL instance on port: $1
  echo "Creating volume: pg-data-$1"
  docker volume create pg-data-$1
  echo "Starting container: pg-$1"
  docker run --restart always --name pg-$1 -v pg-data-$1:/var/lib/postgresql/data -p $1:5432 -p $2:80 --env-file $1.env -it burggraf/tiny-pg
else
  echo "usage: ./tiny-pg <port>"
  echo "example: ./tiny-pg 5001"
fi
