#!/bin/sh
if [ "`which docker`" = "" ]; then
  echo "Docker command line tool is not installed. Aborting..."
  exit 1
else
  DOCKER=`docker -v | sed 's/\(.*\) \(.*\), \(.*\) .*/\2/'`
  echo "Found docker version: $DOCKER"
fi
if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null; then
  if [ "$(docker ps | grep pg-$1)" ]; then
      echo "Container pg-$1 is running."
      echo "We'll log you in to the container and start up psql:"
      docker exec -it pg-$1 /bin/sh -c "psql -U postgres;/bin/sh"
      exit 0
  else
    if [ "$(docker ps -a | grep pg-$1)" ]; then
        echo "Container pg-$1 exists, but is not running."
        echo "Starting container: pg-$1"
        docker start pg-$1
        sleep 2
        echo "We'll log you in to the container and start up psql:"
        docker exec -it pg-$1 /bin/sh -c "psql -U postgres;/bin/sh"
        exit 0
    else
        echo "Container pg-$1 does not exist."
    fi
  fi

  echo Starting PostgreSQL instance on port: $1
  echo "Creating volume: pg-data-$1"
  docker volume create pg-data-$1
  echo "Starting container: pg-$1"
  docker run --restart always --name pg-$1 -v pg-data-$1:/var/lib/postgresql/data -p $1:5432 -p $2:80 -it burggraf/tiny-pg
else
  echo "usage: ./tiny-pg <port> <admin port> (admin port is optional)"
  echo "example: ./tiny-pg 5001 6001"
fi
